services:
  api:
    build: .
    container_name: nfe-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/nfe_db?authSource=admin
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_PROJECT_ID: ${GEMINI_PROJECT_ID}
    networks:
      - backend
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo:latest
    container_name: nfe-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  chroma:
    image: chromadb/chroma:latest
    container_name: nfe-chromadb
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/app/chroma_data
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
  chroma-data:

networks:
  backend:
    driver: bridge