server:
  port: 8080

spring:
  application:
    name: assistente-contabil

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID}
          location: southamerica-east1
          api-key: ${GEMINI_API_KEY}

  vectorstore:
    chroma:
      url: http://chroma:8000
      collection: nfe-embeddings

api:
  gemini:
    token: ${API_GEMINI_TOKEN}




#nfe:
#  xml:
#    input:
#      directory: /app/nfe_entrada_simulacao
