server:
  port: 8080

spring:
  application:
    name: assistente-contabil

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

api:
  gemini:
    token: ${API_GEMINI_TOKEN}

#nfe:
#  xml:
#    input:
#      directory: /app/nfe_entrada_simulacao
